---
driver:
  name: vagrant
  customize:
    memory: 1048

provisioner:
  name: chef_solo
  attributes:
    zookeeperd:
      cluster:
        auto_discovery: false
      config:
        client_port: 9000

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: centos-6.4

suites:
  - name: client
    run_list:
      - recipe[zookeeperd]
  - name: server
    run_list:
      - recipe[zookeeperd::server]
  - name: server-cloudera
    includes:
      - ubuntu-12.04
    run_list:
      - recipe[zookeeperd::server]
    attributes:
      zookeeperd:
        cloudera_repo: true
  - name: server-runit
    run_list:
      - recipe[zookeeperd::server]
    attributes:
      zookeeperd:
        service: runit
  - name: server-cloudera-runit
    includes:
      - ubuntu-12.04
    run_list:
      - recipe[zookeeperd::server]
    attributes:
      zookeeperd:
        cloudera_repo: true
        service: runit
  - name: server-jar
    run_list:
      - recipe[zookeeperd::server]
    attributes:
      zookeeperd:
        install:
          method: 'jar'
        jar:
          download:
            version: '3.3.6'
